version: '3'

services:
  node1:
    container_name: node1
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./vpn-client:/app
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      - net1

  node2:
    container_name: node2
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
     - ./vpn-client:/app
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      - net1

networks:
  net1:
    name: net1
